-- =============================================================================
-- WKND Sample Website — 06: Magazine section + 5 articles
-- Run order: after 04_home.sql
-- =============================================================================

-- Magazine section root
INSERT INTO content_nodes (id, path, name, resource_type, parent_path, properties, status, site_id, locale, created_by, modified_by)
VALUES
(md5('wknd-page-magazine')::uuid,
 'wknd.language-masters.en.magazine',
 'magazine', 'wknd/components/page',
 'wknd.language-masters.en',
 '{
   "title": "Magazine",
   "description": "Stories, guides and inspiration from WKND contributors around the world.",
   "template": "wknd/templates/landing-page",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"header-title","resourceType":"wknd/components/title","data":{"title":"Magazine","type":"h1"}},
       {"name":"intro","resourceType":"wknd/components/text","data":{
         "text":"<p>Real stories from real adventurers. Surf reports, travel guides and cultural deep-dives from our global community of contributors.</p>",
         "textIsRich":true
       }},
       {"name":"articles-list","resourceType":"wknd/components/image-list","data":{
         "listFrom":"children",
         "parentPage":"/wknd/language-masters/en/magazine",
         "orderBy":"modified_at",
         "sortOrder":"desc"
       }}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install')
ON CONFLICT (path) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Magazine articles
-- ---------------------------------------------------------------------------
INSERT INTO content_nodes (id, path, name, resource_type, parent_path, properties, status, site_id, locale, created_by, modified_by)
VALUES

-- 1. Arctic Surfing
(md5('wknd-art-arctic')::uuid,
 'wknd.language-masters.en.magazine.arctic-surfing',
 'arctic-surfing', 'wknd/components/page',
 'wknd.language-masters.en.magazine',
 '{
   "title": "Arctic Surfing in the Lofoten Islands",
   "description": "Chasing cold, hollow barrels inside the Arctic Circle — Norway''s Lofoten Islands are the most dramatic surf destination on the planet.",
   "template": "wknd/templates/article-page",
   "thumbnail": "/content/dam/wknd-shared/en/magazine/arctic-surfing/arctic-surfing-hero.jpeg",
   "author": "Jacob Wester",
   "authorXfPath": "experience-fragments.wknd.language-masters.en.contributors.jacob-wester.byline",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"breadcrumb","resourceType":"wknd/components/breadcrumb","data":{"startLevel":4}},
       {"name":"hero","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/arctic-surfing/arctic-surfing-hero.jpeg",
         "alt":"Arctic surfing in the Lofoten Islands"
       }},
       {"name":"title","resourceType":"wknd/components/title","data":{"title":"Arctic Surfing in the Lofoten Islands","type":"h1"}},
       {"name":"byline","resourceType":"flexcms/experience-fragment","data":{"fragmentPath":"experience-fragments.wknd.language-masters.en.contributors.jacob-wester.byline"}},
       {"name":"intro","resourceType":"wknd/components/text","data":{
         "text":"<p>The Lofoten Islands sit above the Arctic Circle and are battered by swells generated by storms spinning across the North Atlantic. The waves here are cold, powerful and incredibly photogenic.</p>",
         "textIsRich":true
       }},
       {"name":"body","resourceType":"wknd/components/text","data":{
         "text":"<p>Getting to Lofoten requires commitment — a flight to Bodø, then a ferry or mountain road drive. But the reward is world-class surf in the shadow of jagged peaks with the northern lights as a backdrop in winter.</p><p>The main surf spot, Unstad Beach, faces north-west and picks up the full force of Atlantic groundswells. It works from 2 ft to double overhead and suits all levels.</p>",
         "textIsRich":true
       }},
       {"name":"image2","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/arctic-surfing/arctic-surfing-unstad.jpeg",
         "alt":"Unstad Beach, Lofoten"
       }},
       {"name":"separator","resourceType":"wknd/components/separator","data":{}},
       {"name":"related-title","resourceType":"wknd/components/title","data":{"title":"More Adventures","type":"h3"}},
       {"name":"related","resourceType":"wknd/components/image-list","data":{
         "listFrom":"static",
         "pages":["/wknd/language-masters/en/adventures/bali-surf-camp","/wknd/language-masters/en/adventures/surf-camp-costa-rica"]
       }}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install'),

-- 2. Guide to LA Skateparks
(md5('wknd-art-la-skate')::uuid,
 'wknd.language-masters.en.magazine.guide-la-skateparks',
 'guide-la-skateparks', 'wknd/components/page',
 'wknd.language-masters.en.magazine',
 '{
   "title": "A Guide to the Best Skateparks in LA",
   "description": "From Venice Beach to Koreatown, Los Angeles has some of the finest skateparks in the world. Here is our insider guide.",
   "template": "wknd/templates/article-page",
   "thumbnail": "/content/dam/wknd-shared/en/magazine/la-skate-parks/adobestock-171095111.jpeg",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"breadcrumb","resourceType":"wknd/components/breadcrumb","data":{"startLevel":4}},
       {"name":"hero","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/la-skate-parks/adobestock-171095111.jpeg",
         "alt":"Los Angeles Skateparks"
       }},
       {"name":"title","resourceType":"wknd/components/title","data":{"title":"A Guide to the Best Skateparks in LA","type":"h1"}},
       {"name":"intro","resourceType":"wknd/components/text","data":{
         "text":"<p>Los Angeles is the birthplace of modern skate culture. From the legendary pools of Dogtown to today''s world-class concrete parks, the city remains a global skate mecca.</p>",
         "textIsRich":true
       }},
       {"name":"body","resourceType":"wknd/components/text","data":{
         "text":"<h2>Venice Beach Skate Park</h2><p>The most iconic skatepark in the world sits right on the beach. The bowls and street section are free to use and open daily.</p><h2>Stoner Skate Plaza</h2><p>Hidden in West LA, Stoner is a technical street plaza favoured by locals. Less crowded than Venice and excellent for ledge and rail skating.</h2><h2>Hollenbeck Skatepark</h2><p>East LA''s premier concrete bowl. Deep and challenging, this park rewards experienced skaters with smooth walls and good flow.</p>",
         "textIsRich":true
       }},
       {"name":"separator","resourceType":"wknd/components/separator","data":{}}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install'),

-- 3. San Diego Surf
(md5('wknd-art-sandiego')::uuid,
 'wknd.language-masters.en.magazine.san-diego-surf',
 'san-diego-surf', 'wknd/components/page',
 'wknd.language-masters.en.magazine',
 '{
   "title": "San Diego''s Best Surf Spots",
   "description": "From the reef breaks of Black''s Beach to the beach breaks of Pacific Beach — the complete guide to surfing San Diego.",
   "template": "wknd/templates/article-page",
   "thumbnail": "/content/dam/wknd-shared/en/magazine/san-diego-surf-spots/beach-walking.jpg",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"breadcrumb","resourceType":"wknd/components/breadcrumb","data":{"startLevel":4}},
       {"name":"hero","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/san-diego-surf-spots/beach-walking.jpg",
         "alt":"San Diego beach"
       }},
       {"name":"title","resourceType":"wknd/components/title","data":{"title":"San Diego''s Best Surf Spots","type":"h1"}},
       {"name":"body","resourceType":"wknd/components/text","data":{
         "text":"<h2>Black''s Beach</h2><p>The most powerful wave in San Diego breaks over a reef shelf below the Torrey Pines cliffs. Access via a steep trail adds to the mystique.</p><h2>Ocean Beach</h2><p>A consistent beach break with multiple peaks. The OB pier area is a classic.</p><h2>Pacific Beach</h2><p>A 3-mile stretch of fun, forgiving surf suited to beginners and intermediates.</p>",
         "textIsRich":true
       }},
       {"name":"separator","resourceType":"wknd/components/separator","data":{}}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install'),

-- 4. Ski Touring
(md5('wknd-art-skitouring')::uuid,
 'wknd.language-masters.en.magazine.ski-touring',
 'ski-touring', 'wknd/components/page',
 'wknd.language-masters.en.magazine',
 '{
   "title": "Ski Touring: Getting Started",
   "description": "Everything you need to know to transition from resort skiing to the backcountry — gear, technique and safety.",
   "template": "wknd/templates/article-page",
   "thumbnail": "/content/dam/wknd-shared/en/magazine/ski-touring/ski-touring-hero.jpeg",
   "author": "Jacob Wester",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"breadcrumb","resourceType":"wknd/components/breadcrumb","data":{"startLevel":4}},
       {"name":"hero","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/ski-touring/ski-touring-hero.jpeg",
         "alt":"Ski touring in the Alps"
       }},
       {"name":"title","resourceType":"wknd/components/title","data":{"title":"Ski Touring: Getting Started","type":"h1"}},
       {"name":"byline","resourceType":"flexcms/experience-fragment","data":{"fragmentPath":"experience-fragments.wknd.language-masters.en.contributors.jacob-wester.byline"}},
       {"name":"body","resourceType":"wknd/components/text","data":{
         "text":"<h2>The Gear</h2><p>You''ll need AT bindings or a splitboard, skins for ascent and an avalanche safety kit: beacon, probe, shovel. All three are non-negotiable.</p><h2>The Technique</h2><p>Efficient skinning is about steady rhythm and minimal wasted energy. Keep your body upright and your strides long and smooth.</p><h2>Safety First</h2><p>Always check the avalanche forecast. Take an avalanche rescue course before your first backcountry trip.</p>",
         "textIsRich":true
       }},
       {"name":"separator","resourceType":"wknd/components/separator","data":{}}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install'),

-- 5. Camping Western Australia
(md5('wknd-art-western-aus')::uuid,
 'wknd.language-masters.en.magazine.western-australia',
 'western-australia', 'wknd/components/page',
 'wknd.language-masters.en.magazine',
 '{
   "title": "Camping in Western Australia",
   "description": "A remote paradise in the south-west of Western Australia, where golden beaches meet ancient forests.",
   "template": "wknd/templates/article-page",
   "thumbnail": "/content/dam/wknd-shared/en/magazine/western-australia/adobestock-156407519.jpeg",
   "components": [
     {"name":"root","resourceType":"wknd/components/container","data":{},"children":[
       {"name":"breadcrumb","resourceType":"wknd/components/breadcrumb","data":{"startLevel":4}},
       {"name":"hero","resourceType":"wknd/components/image","data":{
         "fileReference":"/content/dam/wknd-shared/en/magazine/western-australia/adobestock-156407519.jpeg",
         "alt":"Western Australia coastline"
       }},
       {"name":"title","resourceType":"wknd/components/title","data":{"title":"Camping in Western Australia","type":"h1"}},
       {"name":"body","resourceType":"wknd/components/text","data":{
         "text":"<h2>The South-West</h2><p>The south-west corner of WA is one of the world''s 35 biodiversity hotspots. Towering karri forests, white sand beaches and turquoise Indian Ocean waters all within an hour''s drive of Margaret River.</p><h2>Best Campsites</h2><p>Boranup Campground sits inside the karri forest just 1 km from Hamelin Bay. Green''s Pool at William Bay National Park is one of the most beautiful sheltered swimming spots in Australia.</p>",
         "textIsRich":true
       }},
       {"name":"separator","resourceType":"wknd/components/separator","data":{}}
     ]}
   ]
 }'::jsonb,
 'LIVE', 'wknd', 'en', 'wknd-install', 'wknd-install')

ON CONFLICT (path) DO NOTHING;
