/**
 * Generated by `src/capture/generateTraceabilitySkeletons.ts` for REB-06.
 * Do not hand-edit; regenerate with `pnpm generate:traceability`.
 */
export interface ComponentManifestEntry {
  caseId: string;
  slug: string;
  title: string;
  captureStatus: 'captured' | 'skipped';
  manifestPath: string;
  normalizedHtml: string;
  screenshotEvidence: string;
  blockerCount: number;
}

export const componentManifest: ComponentManifestEntry[] = [
  {
    "caseId": "CMP-01",
    "slug": "component_library_account_transactional",
    "title": "Account Transactional",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_account_transactional/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_account_transactional/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_account_transactional/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-02",
    "slug": "component_library_commerce_merchandising",
    "title": "Commerce Merchandising",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_commerce_merchandising/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_commerce_merchandising/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_commerce_merchandising/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-03",
    "slug": "component_library_community_engagement",
    "title": "Community Engagement",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_community_engagement/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_community_engagement/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_community_engagement/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-04",
    "slug": "component_library_corporate_investor",
    "title": "Corporate Investor",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_corporate_investor/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_corporate_investor/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_corporate_investor/capture-evidence.png",
    "blockerCount": 3
  },
  {
    "caseId": "CMP-05",
    "slug": "component_library_ctas_promotions",
    "title": "Ctas Promotions",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_ctas_promotions/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_ctas_promotions/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_ctas_promotions/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-06",
    "slug": "component_library_editorial_article_content",
    "title": "Editorial & Article Content",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_editorial_article_content/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_editorial_article_content/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_editorial_article_content/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-07",
    "slug": "component_library_education_learning",
    "title": "Education Learning",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_education_learning/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_education_learning/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_education_learning/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-08",
    "slug": "component_library_events_booking",
    "title": "Events Booking",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_events_booking/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_events_booking/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_events_booking/capture-evidence.png",
    "blockerCount": 2
  },
  {
    "caseId": "CMP-09",
    "slug": "component_library_forms_consent",
    "title": "Forms Consent",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_forms_consent/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_forms_consent/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_forms_consent/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-10",
    "slug": "component_library_layout_page_structure",
    "title": "Layout & Page Structure",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_layout_page_structure/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_layout_page_structure/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_layout_page_structure/capture-evidence.png",
    "blockerCount": 2
  },
  {
    "caseId": "CMP-11",
    "slug": "component_library_location_presence",
    "title": "Location Presence",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_location_presence/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_location_presence/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_location_presence/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-12",
    "slug": "component_library_media_assets",
    "title": "Media Assets",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_media_assets/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_media_assets/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_media_assets/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-13",
    "slug": "component_library_navigation_discovery",
    "title": "Navigation Discovery",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/components/component_library_navigation_discovery/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/components/component_library_navigation_discovery/normalized.html",
    "screenshotEvidence": "Design/tut-usa/components/component_library_navigation_discovery/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "CMP-14",
    "slug": "tut_sovereign",
    "title": "Tut Sovereign",
    "captureStatus": "skipped",
    "manifestPath": "",
    "normalizedHtml": "",
    "screenshotEvidence": "",
    "blockerCount": 0
  }
];
