/**
 * Generated by `src/capture/generateTraceabilitySkeletons.ts` for REB-06.
 * Do not hand-edit; regenerate with `pnpm generate:traceability`.
 */
export interface TemplateSeedMapEntry {
  caseId: string;
  slug: string;
  seededUrlPaths: string[];
}

export const templateSeedMap: TemplateSeedMapEntry[] = [
  {
    "caseId": "TPL-01",
    "slug": "accessories_lifestyle_collection_page",
    "seededUrlPaths": [
      "/tut-usa/accessories",
      "/tut-usa/accessories/accessories-overview",
      "/tut-usa/accessories/interior-accessories",
      "/tut-usa/accessories/lifestyle-collection",
      "/tut-usa/accessories/performance-accessories"
    ]
  },
  {
    "caseId": "TPL-02",
    "slug": "book_a_test_drive_page",
    "seededUrlPaths": [
      "/tut-usa/offers-and-finance/book-a-test-drive"
    ]
  },
  {
    "caseId": "TPL-03",
    "slug": "brand_story_about_tut_page",
    "seededUrlPaths": [
      "/tut-usa/innovation"
    ]
  },
  {
    "caseId": "TPL-04",
    "slug": "build_configure_page",
    "seededUrlPaths": [
      "/tut-usa/vehicles/build-and-configure",
      "/tut-usa/vehicles/electric-vehicles/tut-eon/build-tut-eon",
      "/tut-usa/vehicles/sedans/tut-e/build-tut-e",
      "/tut-usa/vehicles/sedans/tut-s/build-tut-s",
      "/tut-usa/vehicles/suvs/tut-q/build-tut-q",
      "/tut-usa/vehicles/suvs/tut-x/build-tut-x"
    ]
  },
  {
    "caseId": "TPL-05",
    "slug": "compare_models_page",
    "seededUrlPaths": [
      "/tut-usa/vehicles/compare-vehicles",
      "/tut-usa/vehicles/electric-vehicles/tut-eon/compare-tut-eon",
      "/tut-usa/vehicles/sedans/tut-s/compare-tut-s",
      "/tut-usa/vehicles/suvs/tut-x/compare-tut-x"
    ]
  },
  {
    "caseId": "TPL-06",
    "slug": "contact_concierge_page",
    "seededUrlPaths": []
  },
  {
    "caseId": "TPL-07",
    "slug": "dealer_showroom_locator_page",
    "seededUrlPaths": [
      "/tut-usa/offers-and-finance/find-a-dealer"
    ]
  },
  {
    "caseId": "TPL-08",
    "slug": "global_home_page",
    "seededUrlPaths": [
      "/tut-usa",
      "/tut-usa/home"
    ]
  },
  {
    "caseId": "TPL-09",
    "slug": "innovation_feature_detail_page",
    "seededUrlPaths": [
      "/tut-usa/innovation/connectivity-and-digital-cabin",
      "/tut-usa/innovation/craftsmanship-and-materials",
      "/tut-usa/innovation/driver-assistance",
      "/tut-usa/innovation/electrification",
      "/tut-usa/innovation/performance-engineering",
      "/tut-usa/learn/feature-explainer-article"
    ]
  },
  {
    "caseId": "TPL-10",
    "slug": "innovation_hub_page",
    "seededUrlPaths": [
      "/tut-usa/innovation",
      "/tut-usa/innovation/innovation-overview"
    ]
  },
  {
    "caseId": "TPL-11",
    "slug": "learning_education_hub_page",
    "seededUrlPaths": [
      "/tut-usa/learn",
      "/tut-usa/learn/ev-buying-guide",
      "/tut-usa/learn/learning-overview",
      "/tut-usa/learn/model-comparison-guide"
    ]
  },
  {
    "caseId": "TPL-12",
    "slug": "model_overview_page",
    "seededUrlPaths": [
      "/tut-usa/vehicles",
      "/tut-usa/vehicles/electric-vehicles",
      "/tut-usa/vehicles/sedans",
      "/tut-usa/vehicles/suvs",
      "/tut-usa/vehicles/vehicle-lineup"
    ]
  },
  {
    "caseId": "TPL-13",
    "slug": "news_press_article_detail_page",
    "seededUrlPaths": [
      "/tut-usa/news-and-updates/event-coverage-article",
      "/tut-usa/news-and-updates/press-release-article",
      "/tut-usa/news-and-updates/product-launch-article"
    ]
  },
  {
    "caseId": "TPL-14",
    "slug": "news_updates_landing_page",
    "seededUrlPaths": [
      "/tut-usa/news-and-updates",
      "/tut-usa/news-and-updates/news-landing"
    ]
  },
  {
    "caseId": "TPL-15",
    "slug": "offers_financing_leasing_page",
    "seededUrlPaths": [
      "/tut-usa/offers-and-finance",
      "/tut-usa/offers-and-finance/financing-and-leasing",
      "/tut-usa/offers-and-finance/offers-and-incentives"
    ]
  },
  {
    "caseId": "TPL-16",
    "slug": "owner_manual_technical_documentation_page",
    "seededUrlPaths": [
      "/tut-usa/owners/manuals-and-technical-documents"
    ]
  },
  {
    "caseId": "TPL-17",
    "slug": "owners_hub_landing_page",
    "seededUrlPaths": [
      "/tut-usa/owners",
      "/tut-usa/owners/owners-overview"
    ]
  },
  {
    "caseId": "TPL-18",
    "slug": "safety_charging_ownership_how_to_page",
    "seededUrlPaths": [
      "/tut-usa/learn/ownership-how-to-article",
      "/tut-usa/owners/charging-and-ev-ownership",
      "/tut-usa/owners/safety-and-assistance-how-to"
    ]
  },
  {
    "caseId": "TPL-19",
    "slug": "service_maintenance_page",
    "seededUrlPaths": [
      "/tut-usa/owners/service-and-maintenance",
      "/tut-usa/owners/warranty-and-coverage"
    ]
  },
  {
    "caseId": "TPL-20",
    "slug": "tut_sovereign",
    "seededUrlPaths": []
  },
  {
    "caseId": "TPL-21",
    "slug": "vehicle_model_detail_page",
    "seededUrlPaths": [
      "/tut-usa/vehicles/electric-vehicles/tut-eon",
      "/tut-usa/vehicles/sedans/tut-e",
      "/tut-usa/vehicles/sedans/tut-s",
      "/tut-usa/vehicles/suvs/tut-q",
      "/tut-usa/vehicles/suvs/tut-x"
    ]
  }
];
