/**
 * Generated by `src/capture/generateTraceabilitySkeletons.ts` for REB-06.
 * Do not hand-edit; regenerate with `pnpm generate:traceability`.
 */
export interface TemplateManifestEntry {
  caseId: string;
  slug: string;
  title: string;
  captureStatus: 'captured' | 'skipped';
  manifestPath: string;
  normalizedHtml: string;
  screenshotEvidence: string;
  blockerCount: number;
}

export const templateManifest: TemplateManifestEntry[] = [
  {
    "caseId": "TPL-01",
    "slug": "accessories_lifestyle_collection_page",
    "title": "Accessories / Lifestyle Collection Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/accessories_lifestyle_collection_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/accessories_lifestyle_collection_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/accessories_lifestyle_collection_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-02",
    "slug": "book_a_test_drive_page",
    "title": "Book a Test Drive Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/book_a_test_drive_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/book_a_test_drive_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/book_a_test_drive_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-03",
    "slug": "brand_story_about_tut_page",
    "title": "Brand Story / About TUT Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/brand_story_about_tut_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/brand_story_about_tut_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/brand_story_about_tut_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-04",
    "slug": "build_configure_page",
    "title": "Build & Configure Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/build_configure_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/build_configure_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/build_configure_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-05",
    "slug": "compare_models_page",
    "title": "Compare Models Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/compare_models_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/compare_models_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/compare_models_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-06",
    "slug": "contact_concierge_page",
    "title": "Contact / Concierge / Support Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/contact_concierge_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/contact_concierge_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/contact_concierge_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-07",
    "slug": "dealer_showroom_locator_page",
    "title": "Dealer / Showroom Locator Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/dealer_showroom_locator_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/dealer_showroom_locator_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/dealer_showroom_locator_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-08",
    "slug": "global_home_page",
    "title": "Global Home Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/global_home_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/global_home_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/global_home_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-09",
    "slug": "innovation_feature_detail_page",
    "title": "Innovation Feature Detail Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/innovation_feature_detail_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/innovation_feature_detail_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/innovation_feature_detail_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-10",
    "slug": "innovation_hub_page",
    "title": "Innovation Hub Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/innovation_hub_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/innovation_hub_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/innovation_hub_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-11",
    "slug": "learning_education_hub_page",
    "title": "Learning / Education Hub Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/learning_education_hub_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/learning_education_hub_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/learning_education_hub_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-12",
    "slug": "model_overview_page",
    "title": "Model Overview / Lineup Landing Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/model_overview_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/model_overview_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/model_overview_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-13",
    "slug": "news_press_article_detail_page",
    "title": "News / Press / Article Detail Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/news_press_article_detail_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/news_press_article_detail_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/news_press_article_detail_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-14",
    "slug": "news_updates_landing_page",
    "title": "News & Updates Landing Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/news_updates_landing_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/news_updates_landing_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/news_updates_landing_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-15",
    "slug": "offers_financing_leasing_page",
    "title": "Offers / Financing / Leasing Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/offers_financing_leasing_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/offers_financing_leasing_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/offers_financing_leasing_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-16",
    "slug": "owner_manual_technical_documentation_page",
    "title": "Owner Manual / Technical Documentation Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/owner_manual_technical_documentation_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/owner_manual_technical_documentation_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/owner_manual_technical_documentation_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-17",
    "slug": "owners_hub_landing_page",
    "title": "Owners Hub Landing Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/owners_hub_landing_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/owners_hub_landing_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/owners_hub_landing_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-18",
    "slug": "safety_charging_ownership_how_to_page",
    "title": "Safety, Charging & Ownership How-To Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/safety_charging_ownership_how_to_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/safety_charging_ownership_how_to_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/safety_charging_ownership_how_to_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-19",
    "slug": "service_maintenance_page",
    "title": "Service & Maintenance Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/service_maintenance_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/service_maintenance_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/service_maintenance_page/capture-evidence.png",
    "blockerCount": 1
  },
  {
    "caseId": "TPL-20",
    "slug": "tut_sovereign",
    "title": "Tut Sovereign",
    "captureStatus": "skipped",
    "manifestPath": "",
    "normalizedHtml": "",
    "screenshotEvidence": "",
    "blockerCount": 0
  },
  {
    "caseId": "TPL-21",
    "slug": "vehicle_model_detail_page",
    "title": "Vehicle Model Detail Page",
    "captureStatus": "captured",
    "manifestPath": "Design/tut-usa/templates/vehicle_model_detail_page/assets-manifest.json",
    "normalizedHtml": "Design/tut-usa/templates/vehicle_model_detail_page/normalized.html",
    "screenshotEvidence": "Design/tut-usa/templates/vehicle_model_detail_page/capture-evidence.png",
    "blockerCount": 1
  }
];
