/**
 * Reference site component map — registers React renderers for each CMS component type.
 * This is where the frontend team maps backend resourceTypes to React components.
 *
 * The backend team defines the data schema (the contract).
 * The frontend team builds the renderer (this file).
 * Neither side touches the other's code.
 */
'use client';

import { ComponentMapper } from '@flexcms/sdk';
import type { FlexCmsRenderer } from '@flexcms/react';

// ---------------------------------------------------------------------------
// Core component renderers
// ---------------------------------------------------------------------------

/** flexcms/rich-text — renders HTML content */
function RichText({ data }: { data: Record<string, unknown> }) {
  return (
    <div
      className="prose max-w-none"
      dangerouslySetInnerHTML={{ __html: (data.content as string) ?? '' }}
    />
  );
}

/** flexcms/image — renders a responsive image */
function Image({ data }: { data: Record<string, unknown> }) {
  return (
    <figure>
      <img
        src={data.src as string}
        alt={(data.alt as string) ?? ''}
        width={data.width as number}
        height={data.height as number}
        loading="lazy"
      />
      {data.caption != null && <figcaption>{String(data.caption)}</figcaption>}
    </figure>
  );
}

/** flexcms/container — renders children in a layout */
function Container({ data, children }: { data: Record<string, unknown>; children?: React.ReactNode }) {
  const layout = (data.layout as string) ?? 'single';
  const layoutClass = {
    single: '',
    'two-equal': 'grid grid-cols-2 gap-6',
    'three-equal': 'grid grid-cols-3 gap-6',
  }[layout] ?? '';

  return <div className={layoutClass}>{children}</div>;
}

/** flexcms/shared-header — site header */
function Header({ data }: { data: Record<string, unknown> }) {
  return (
    <header className="border-b py-4 px-6">
      <nav className="flex items-center gap-6">
        <strong>{(data.logo as string) ?? 'FlexCMS Site'}</strong>
      </nav>
    </header>
  );
}

/** flexcms/shared-footer — site footer */
function Footer({ data }: { data: Record<string, unknown> }) {
  return (
    <footer className="border-t py-8 px-6 text-center text-sm text-gray-500">
      © {new Date().getFullYear()} FlexCMS Site
    </footer>
  );
}

// ---------------------------------------------------------------------------
// TUT component renderers
// ---------------------------------------------------------------------------

export { HeroBanner } from './tut/HeroBanner';
export { TextImage } from './tut/TextImage';
export { CardGrid } from './tut/CardGrid';
export { Card } from './tut/Card';
export { ProductTeaser } from './tut/ProductTeaser';
export { ProductSpecs } from './tut/ProductSpecs';
export { Gallery } from './tut/Gallery';
export { CtaBanner } from './tut/CtaBanner';
export { Accordion } from './tut/Accordion';
export { AccordionItem } from './tut/AccordionItem';
export { VideoEmbed } from './tut/VideoEmbed';
export { Navigation } from './tut/Navigation';
export { Breadcrumb } from './tut/Breadcrumb';
export { FooterLinks } from './tut/FooterLinks';
export { LanguageSelector } from './tut/LanguageSelector';
export { StatCounter } from './tut/StatCounter';
export { Testimonial } from './tut/Testimonial';
export { ModelComparison } from './tut/ModelComparison';

import { HeroBanner } from './tut/HeroBanner';
import { TextImage } from './tut/TextImage';
import { CardGrid } from './tut/CardGrid';
import { Card } from './tut/Card';
import { ProductTeaser } from './tut/ProductTeaser';
import { ProductSpecs } from './tut/ProductSpecs';
import { Gallery } from './tut/Gallery';
import { CtaBanner } from './tut/CtaBanner';
import { Accordion } from './tut/Accordion';
import { AccordionItem } from './tut/AccordionItem';
import { VideoEmbed } from './tut/VideoEmbed';
import { Navigation } from './tut/Navigation';
import { Breadcrumb } from './tut/Breadcrumb';
import { FooterLinks } from './tut/FooterLinks';
import { LanguageSelector } from './tut/LanguageSelector';
import { StatCounter } from './tut/StatCounter';
import { Testimonial } from './tut/Testimonial';
import { ModelComparison } from './tut/ModelComparison';
import {
  SearchBar,
  SearchResults,
  TutUsaBreadcrumb,
  TutUsaNavigation,
  PrimaryNavigation,
  LinksGroupNavigation,
  MegaMenu,
  SecondaryNavigation,
  TutUsaFooter,
  LinksGroupFooter,
  TutUsaLogo,
  AccountSignIn,
  TutUsaSiteMap,
  BackToTop,
  SideNavigation,
  AnchorLinks,
  TextLink,
  ButtonGroup,
  LinkList,
  RelatedContent,
  RecommendedArticles,
  CategoryCard,
  CategoryGrid,
  BookmarkButton,
  SkipLink,
  LanguageSwitcher,
  CountrySelector,
  CurrencySelector,
} from './tut-usa/navigation';
import {
  HtmlEmbed,
  Carousel,
  ContentSlider,
  ImageGallery,
  LightboxGallery,
  BeforeAfterImage,
  ImageWithCaption,
  VideoEmbed as TutUsaVideoEmbed,
  AudioPlayer,
  PodcastEpisode,
  TestimonialSlider,
  LogoGrid,
  DocumentDownload,
  BrochureDownload,
  WhitepaperDownload,
  EbookDownload,
  ReportDownload,
  MasonryGallery,
  InfographicEmbed,
  ChartEmbed,
  DownloadCenter,
  AssetDetail,
  MediaLibraryCard,
  BrandGuidelineSection,
  ColorPalette,
  TypographyGuide,
  IconLibrary,
  DesignTokenTable,
  BrandAssetDownload,
  PressKit,
  MediaCoverageCard,
  ResourceCard,
  ResourceList,
} from './tut-usa/media';
import {
  RichTextBlock,
  PlainTextBlock,
  Heading,
  Subheading,
  Paragraph,
  Quote,
  PullQuote,
  CodeSnippet,
  MarkdownBlock,
  Accordion as EditorialAccordion,
  Tabs,
  Table,
  DataTable,
  DefinitionList,
  Checklist,
  NumberedSteps,
  Timeline,
  StatCounter as EditorialStatCounter,
  KpiCard,
  FactBox,
  CaseStudyTeaser,
  CaseStudyDetail,
  Faq,
  FaqItem,
  KnowledgeBaseArticle,
  HowToGuide,
  GlossaryEntry,
  LatestNews,
  NewsCard,
  ArticleCard,
  ArticleDetail,
  BlogPost,
  BlogListing,
  PressRelease,
  FeatureList,
  FeatureComparison,
  StoryCard,
  MilestoneCard,
  RoadmapCard,
  MilestoneTimeline,
  FactSheet,
  ExecutiveProfile,
  BoardMemberProfile,
  LeadershipGrid,
  CsrHighlight,
  EsgMetric,
  ImpactStory,
  PublicationCitation,
  ResearchPaperDetail,
  DatasetDownload,
  MethodologyNote,
  LabResultSummary,
  ComplianceChecklist,
  RiskIndicator,
  IncidentReport,
  RunbookSection,
  KnowledgePanel,
  QuickLinks,
  BenchmarkTable,
  ReferenceLinkCard,
  ReadingProgress,
  EstimatedReadTime,
  TableOfContents,
  FootnoteList,
  AuthorList,
  RevisionNotice,
  ArchiveNotice,
  ContentRating,
  NewsCardAlt,
} from './tut-usa/editorial';
import {
  AlertBanner,
  InlineAlert,
  AnnouncementBar,
  CtasHeroBanner,
  SplitHero,
  VideoHero,
  ImageBanner,
  PromoBanner,
  CtaButton,
  FeaturedContent,
  NewsletterSignup,
  EmailSignup,
  PricingTable,
  PlanCard,
  CampaignLandingSection,
  PromoTile,
  OfferCard,
  CollectionSpotlight,
  PromoRibbon,
  BundleOffer,
  GiftGuide,
  DonationCta,
  PromoCard,
  SeasonalCampaignBlock,
  BuyerGuide,
  ImplementationPlan,
  SuccessPlan,
  CampaignHero,
  ProductHero,
  EventHero,
  RecruitingHero,
  InvestorHero,
  BrandStoryHero,
  OfferCardAlt,
  TrialSignup,
  DemoRequestCta,
  GiftCardPromo,
  SalesEnablementAsset,
  Battlecard,
  CompetitiveComparisonTable,
  MarketplaceListingCard,
  PersonaShowcase,
  SeasonalHero,
} from './tut-usa/ctas';
import {
  LeadForm,
  ContactForm,
  SupportForm,
  FeedbackForm,
  Survey,
  Poll,
  Quiz,
  Calculator,
  FormFieldText,
  FormFieldTextarea,
  FormFieldEmail,
  FormFieldPhone,
  FormFieldSelect,
  FormFieldRadioGroup,
  FormFieldCheckbox,
  FormFieldCheckboxGroup,
  FormFieldDate,
  FormFieldFileUpload,
  FormFieldConsent,
  CookieBanner,
  PrivacyNotice,
  TermsAndConditions,
  ConsentManager,
  CommentForm,
  ApplicationForm,
  QuoteRequestForm,
  PrescriptionRefillForm,
  ReturnsForm,
  DataRequestForm,
  AgeGate,
  MeetingRequestForm,
  IdeaSubmissionForm,
  HelpfulnessVote,
  ReportIssueLink,
  AccessibilityStatement,
  DoNotSellLink,
  PetitionForm,
  VolunteerSignup,
  MembershipSignup,
  FranchiseInquiryForm,
  WarrantyRegistration,
  VinLookup,
} from './tut-usa/forms';
import {
  ProductCard,
  ProductGrid,
  ProductDetail,
  ProductGallery,
  CommerceProductSpecs,
  ProductVariants,
  AddToCart,
  MiniCart,
  CartSummary,
  CheckoutProgress,
  CouponEntry,
  UpsellRecommendation,
  CrossSell,
  WishlistButton,
  SavedItemsList,
  ReviewSummary,
  ReviewList,
  StarRating,
  ReviewForm,
  ComparisonTool,
  Configurator,
  MerchandiseCard,
  MealPlanCard,
  RecipeCard,
  RecipeDetail,
  NutritionFacts,
  AllergenNotice,
  ReturnsPolicy,
  PreorderCta,
  LicenseSelector,
  ComparisonCard,
} from './tut-usa/commerce';
import {
  LoginForm,
  RegistrationForm,
  PasswordReset,
  ProfileSummary,
  ProfileEditor,
  AddressBlock,
  BillingAddressForm,
  ShippingAddressForm,
  OrderSummary,
  SubscriptionStatus,
  BillingHistory,
  InvoiceDownload,
  PaymentMethodCard,
  PaymentForm,
  LoyaltySummary,
  RewardsCard,
  DashboardWidget,
  StatusBadge,
  PortalShortcut,
  SSOButton,
  PartnerPortalLink,
  EntitlementSummary,
  ReactivationOffer,
  MemberBenefitCard,
} from './tut-usa/account';
import {
  WebinarPromo,
  WebinarReplay,
  EventCard,
  EventList,
  EventDetail,
  Agenda,
  SpeakerProfile,
  BookingWidget,
  AppointmentScheduler,
  ReservationCard,
  Itinerary,
  SeatMap,
  RoomSelector,
  ReservationForm,
  DeliverySlotSelector,
  RoadshowSchedule,
  VenueCard,
  WorkshopCard,
  TrainingSchedule,
  EventCardAlt,
  CommunityEventCard,
  ExpoBoothInfo,
  MenuCard,
  MenuList,
} from './tut-usa/events';
import {
  ContactCard,
  TeamMemberProfile,
  AuthorBio,
  CommunityTestimonial,
  ClientList,
  MediaContact,
  ChatWidget,
  VirtualAssistant,
  SocialShare,
  SocialFollow,
  SocialFeed,
  InstagramGallery,
  LinkedInFeed,
  XFeed,
  TrustBadges,
  CertificationList,
  AwardShowcase,
  PartnerShowcase,
  PartnerDetail,
  CommunityForumTeaser,
  DiscussionThreadPreview,
  Comments,
  UserGeneratedGallery,
  CommunitySpotlight,
  DonorWall,
  MentorProfile,
  ChampionStory,
  VoteCard,
  PartnerFinder,
  PartnerTierBadge,
} from './tut-usa/community';
import {
  InvestorMetric,
  FinancialTable,
  SecFilingDownload,
  EarningsCallPromo,
  InvestorContact,
  ComplianceNotice,
  PolicyDocument,
  DocumentVersionHistory,
  InternalNote,
  OfficeLocation,
  CultureCard,
  BenefitsList,
  GrantOpportunity,
  SponsorShowcase,
  RecallNotice,
  JobListingCard,
  JobListings,
  JobDetail,
  AnalystReportPromo,
  RoadmapSection,
  EscalationMatrix,
} from './tut-usa/corporate';
import {
  MapEmbed,
  LocationCard,
  StoreLocator,
  InteractiveMap,
  BranchLocator,
  AtmLocator,
  ClinicLocator,
  CampusLocation,
  ProviderProfile,
  PickupLocationCard,
  ServiceCenterCard,
  LocationCardAlt,
  DealerLocator,
} from './tut-usa/location';
import {
  CourseCard,
  CourseCatalog,
  LessonDetail,
  CertificateDownload,
  FacultyProfile,
  ProgramOverview,
  ApiDocumentationTeaser,
  ApiEndpointReference,
  SdkDownload,
  SampleCode,
  SandboxAccessCta,
  CertificationPath,
  IntegrationDetail,
  SystemRequirementList,
} from './tut-usa/education';
import {
  SectionDivider,
  Spacer,
  Container as LayoutContainer,
  GridLayout,
  TwoColumnLayout,
  TwoColumnsGrid,
  ThreeColumnLayout,
  CardGrid as LayoutCardGrid,
  SidebarPromo,
  StickyCta,
  ModalDialog,
  SidePanel,
  DrawerNavigation,
  Tooltip,
  Popover,
  Badge,
  MediaObject,
  PageHeader,
  PageFooterSection,
  PageMetadata,
  EmptyState,
  Pagination,
  FilterPanel,
  SortControl,
  TagList,
  IconList,
  IconCard,
  FramedMessage,
  ErrorPage404,
  ErrorPage500,
  ProgressBar,
  StepIndicator,
} from './tut-usa/layout';
import React from 'react';

// ---------------------------------------------------------------------------
// Build the component map (the bridge between contract and rendering)
// ---------------------------------------------------------------------------

export const componentMap = new ComponentMapper<any>()
  .registerAll({
    // Core components
    'flexcms/rich-text': RichText,
    'flexcms/image': Image,
    'flexcms/container': Container,
    'flexcms/shared-header': Header,
    'flexcms/shared-footer': Footer,
    // TUT components
    'tut/hero-banner': HeroBanner,
    'tut/text-image': TextImage,
    'tut/card-grid': CardGrid,
    'tut/card': Card,
    'tut/product-teaser': ProductTeaser,
    'tut/product-specs': ProductSpecs,
    'tut/gallery': Gallery,
    'tut/cta-banner': CtaBanner,
    'tut/accordion': Accordion,
    'tut/accordion-item': AccordionItem,
    'tut/video-embed': VideoEmbed,
    'tut/navigation': Navigation,
    'tut/breadcrumb': Breadcrumb,
    'tut/footer-links': FooterLinks,
    'tut/language-selector': LanguageSelector,
    'tut/stat-counter': StatCounter,
    'tut/testimonial': Testimonial,
    'tut/model-comparison': ModelComparison,
    // TUT USA — Navigation, Search & Discovery
    'tut-usa/navigation-search-discovery/search-bar': SearchBar,
    'tut-usa/navigation-search-discovery/search-results': SearchResults,
    'tut-usa/navigation-search-discovery/breadcrumb': TutUsaBreadcrumb,
    'tut-usa/navigation-search-discovery/navigation': TutUsaNavigation,
    'tut-usa/navigation-search-discovery/primary-navigation': PrimaryNavigation,
    'tut-usa/navigation-search-discovery/links-group-navigation': LinksGroupNavigation,
    'tut-usa/navigation-search-discovery/mega-menu': MegaMenu,
    'tut-usa/navigation-search-discovery/secondary-navigation': SecondaryNavigation,
    'tut-usa/navigation-search-discovery/footer': TutUsaFooter,
    'tut-usa/navigation-search-discovery/links-group-footer': LinksGroupFooter,
    'tut-usa/navigation-search-discovery/logo': TutUsaLogo,
    'tut-usa/navigation-search-discovery/account-sign-in': AccountSignIn,
    'tut-usa/navigation-search-discovery/site-map': TutUsaSiteMap,
    'tut-usa/navigation-search-discovery/back-to-top': BackToTop,
    'tut-usa/navigation-search-discovery/side-navigation': SideNavigation,
    'tut-usa/navigation-search-discovery/anchor-links': AnchorLinks,
    'tut-usa/navigation-search-discovery/text-link': TextLink,
    'tut-usa/navigation-search-discovery/button-group': ButtonGroup,
    'tut-usa/navigation-search-discovery/link-list': LinkList,
    'tut-usa/navigation-search-discovery/related-content': RelatedContent,
    'tut-usa/navigation-search-discovery/recommended-articles': RecommendedArticles,
    'tut-usa/navigation-search-discovery/category-card': CategoryCard,
    'tut-usa/navigation-search-discovery/category-grid': CategoryGrid,
    'tut-usa/navigation-search-discovery/bookmark-button': BookmarkButton,
    'tut-usa/navigation-search-discovery/skip-link': SkipLink,
    'tut-usa/navigation-search-discovery/language-switcher': LanguageSwitcher,
    'tut-usa/navigation-search-discovery/country-selector': CountrySelector,
    'tut-usa/navigation-search-discovery/currency-selector': CurrencySelector,
    // TUT USA — Layout & Page Structure
    'tut-usa/layout-page-structure/section-divider': SectionDivider,
    'tut-usa/layout-page-structure/spacer': Spacer,
    'tut-usa/layout-page-structure/container': LayoutContainer,
    'tut-usa/layout-page-structure/grid-layout': GridLayout,
    'tut-usa/layout-page-structure/two-column-layout': TwoColumnLayout,
    'tut-usa/layout-page-structure/two-columns-grid': TwoColumnsGrid,
    'tut-usa/layout-page-structure/three-column-layout': ThreeColumnLayout,
    'tut-usa/layout-page-structure/card-grid': LayoutCardGrid,
    'tut-usa/layout-page-structure/sidebar-promo': SidebarPromo,
    'tut-usa/layout-page-structure/sticky-cta': StickyCta,
    'tut-usa/layout-page-structure/modal-dialog': ModalDialog,
    'tut-usa/layout-page-structure/side-panel': SidePanel,
    'tut-usa/layout-page-structure/drawer-navigation': DrawerNavigation,
    'tut-usa/layout-page-structure/tooltip': Tooltip,
    'tut-usa/layout-page-structure/popover': Popover,
    'tut-usa/layout-page-structure/badge': Badge,
    'tut-usa/layout-page-structure/media-object': MediaObject,
    'tut-usa/layout-page-structure/page-header': PageHeader,
    'tut-usa/layout-page-structure/page-footer-section': PageFooterSection,
    'tut-usa/layout-page-structure/page-metadata': PageMetadata,
    'tut-usa/layout-page-structure/empty-state': EmptyState,
    'tut-usa/layout-page-structure/pagination': Pagination,
    'tut-usa/layout-page-structure/filter-panel': FilterPanel,
    'tut-usa/layout-page-structure/sort-control': SortControl,
    'tut-usa/layout-page-structure/tag-list': TagList,
    'tut-usa/layout-page-structure/icon-list': IconList,
    'tut-usa/layout-page-structure/icon-card': IconCard,
    'tut-usa/layout-page-structure/framed-message': FramedMessage,
    'tut-usa/layout-page-structure/error-page-404': ErrorPage404,
    'tut-usa/layout-page-structure/error-page-500': ErrorPage500,
    'tut-usa/layout-page-structure/progress-bar': ProgressBar,
    'tut-usa/layout-page-structure/step-indicator': StepIndicator,
    // TUT USA — Editorial & Article Content
    'tut-usa/editorial-article-content/rich-text-block': RichTextBlock,
    'tut-usa/editorial-article-content/plain-text-block': PlainTextBlock,
    'tut-usa/editorial-article-content/heading': Heading,
    'tut-usa/editorial-article-content/subheading': Subheading,
    'tut-usa/editorial-article-content/paragraph': Paragraph,
    'tut-usa/editorial-article-content/quote': Quote,
    'tut-usa/editorial-article-content/pull-quote': PullQuote,
    'tut-usa/editorial-article-content/code-snippet': CodeSnippet,
    'tut-usa/editorial-article-content/markdown-block': MarkdownBlock,
    'tut-usa/editorial-article-content/accordion': EditorialAccordion,
    'tut-usa/editorial-article-content/tabs': Tabs,
    'tut-usa/editorial-article-content/table': Table,
    'tut-usa/editorial-article-content/data-table': DataTable,
    'tut-usa/editorial-article-content/definition-list': DefinitionList,
    'tut-usa/editorial-article-content/checklist': Checklist,
    'tut-usa/editorial-article-content/numbered-steps': NumberedSteps,
    'tut-usa/editorial-article-content/timeline': Timeline,
    'tut-usa/editorial-article-content/stat-counter': EditorialStatCounter,
    'tut-usa/editorial-article-content/kpi-card': KpiCard,
    'tut-usa/editorial-article-content/fact-box': FactBox,
    'tut-usa/editorial-article-content/case-study-teaser': CaseStudyTeaser,
    'tut-usa/editorial-article-content/case-study-detail': CaseStudyDetail,
    'tut-usa/editorial-article-content/faq': Faq,
    'tut-usa/editorial-article-content/faq-item': FaqItem,
    'tut-usa/editorial-article-content/knowledge-base-article': KnowledgeBaseArticle,
    'tut-usa/editorial-article-content/how-to-guide': HowToGuide,
    'tut-usa/editorial-article-content/glossary-entry': GlossaryEntry,
    'tut-usa/editorial-article-content/latest-news': LatestNews,
    'tut-usa/editorial-article-content/news-card': NewsCard,
    'tut-usa/editorial-article-content/article-card': ArticleCard,
    'tut-usa/editorial-article-content/article-detail': ArticleDetail,
    'tut-usa/editorial-article-content/blog-post': BlogPost,
    'tut-usa/editorial-article-content/blog-listing': BlogListing,
    'tut-usa/editorial-article-content/press-release': PressRelease,
    'tut-usa/editorial-article-content/feature-list': FeatureList,
    'tut-usa/editorial-article-content/feature-comparison': FeatureComparison,
    'tut-usa/editorial-article-content/story-card': StoryCard,
    'tut-usa/editorial-article-content/milestone-card': MilestoneCard,
    'tut-usa/editorial-article-content/roadmap-card': RoadmapCard,
    'tut-usa/editorial-article-content/milestone-timeline': MilestoneTimeline,
    'tut-usa/editorial-article-content/fact-sheet': FactSheet,
    'tut-usa/editorial-article-content/executive-profile': ExecutiveProfile,
    'tut-usa/editorial-article-content/board-member-profile': BoardMemberProfile,
    'tut-usa/editorial-article-content/leadership-grid': LeadershipGrid,
    'tut-usa/editorial-article-content/csr-highlight': CsrHighlight,
    'tut-usa/editorial-article-content/esg-metric': EsgMetric,
    'tut-usa/editorial-article-content/impact-story': ImpactStory,
    'tut-usa/editorial-article-content/publication-citation': PublicationCitation,
    'tut-usa/editorial-article-content/research-paper-detail': ResearchPaperDetail,
    'tut-usa/editorial-article-content/dataset-download': DatasetDownload,
    'tut-usa/editorial-article-content/methodology-note': MethodologyNote,
    'tut-usa/editorial-article-content/lab-result-summary': LabResultSummary,
    'tut-usa/editorial-article-content/compliance-checklist': ComplianceChecklist,
    'tut-usa/editorial-article-content/risk-indicator': RiskIndicator,
    'tut-usa/editorial-article-content/incident-report': IncidentReport,
    'tut-usa/editorial-article-content/runbook-section': RunbookSection,
    'tut-usa/editorial-article-content/knowledge-panel': KnowledgePanel,
    'tut-usa/editorial-article-content/quick-links': QuickLinks,
    'tut-usa/editorial-article-content/benchmark-table': BenchmarkTable,
    'tut-usa/editorial-article-content/reference-link-card': ReferenceLinkCard,
    'tut-usa/editorial-article-content/reading-progress': ReadingProgress,
    'tut-usa/editorial-article-content/estimated-read-time': EstimatedReadTime,
    'tut-usa/editorial-article-content/table-of-contents': TableOfContents,
    'tut-usa/editorial-article-content/footnote-list': FootnoteList,
    'tut-usa/editorial-article-content/author-list': AuthorList,
    'tut-usa/editorial-article-content/revision-notice': RevisionNotice,
    'tut-usa/editorial-article-content/archive-notice': ArchiveNotice,
    'tut-usa/editorial-article-content/content-rating': ContentRating,
    'tut-usa/editorial-article-content/news-card-alt': NewsCardAlt,
    // TUT USA — Media, Visual Storytelling & Assets
    'tut-usa/media-visual-storytelling-assets/html-embed': HtmlEmbed,
    'tut-usa/media-visual-storytelling-assets/carousel': Carousel,
    'tut-usa/media-visual-storytelling-assets/content-slider': ContentSlider,
    'tut-usa/media-visual-storytelling-assets/image-gallery': ImageGallery,
    'tut-usa/media-visual-storytelling-assets/lightbox-gallery': LightboxGallery,
    'tut-usa/media-visual-storytelling-assets/before-after-image': BeforeAfterImage,
    'tut-usa/media-visual-storytelling-assets/image-with-caption': ImageWithCaption,
    'tut-usa/media-visual-storytelling-assets/video-embed': TutUsaVideoEmbed,
    'tut-usa/media-visual-storytelling-assets/audio-player': AudioPlayer,
    'tut-usa/media-visual-storytelling-assets/podcast-episode': PodcastEpisode,
    'tut-usa/media-visual-storytelling-assets/testimonial-slider': TestimonialSlider,
    'tut-usa/media-visual-storytelling-assets/logo-grid': LogoGrid,
    'tut-usa/media-visual-storytelling-assets/document-download': DocumentDownload,
    'tut-usa/media-visual-storytelling-assets/brochure-download': BrochureDownload,
    'tut-usa/media-visual-storytelling-assets/whitepaper-download': WhitepaperDownload,
    'tut-usa/media-visual-storytelling-assets/ebook-download': EbookDownload,
    'tut-usa/media-visual-storytelling-assets/report-download': ReportDownload,
    'tut-usa/media-visual-storytelling-assets/masonry-gallery': MasonryGallery,
    'tut-usa/media-visual-storytelling-assets/infographic-embed': InfographicEmbed,
    'tut-usa/media-visual-storytelling-assets/chart-embed': ChartEmbed,
    'tut-usa/media-visual-storytelling-assets/download-center': DownloadCenter,
    'tut-usa/media-visual-storytelling-assets/asset-detail': AssetDetail,
    'tut-usa/media-visual-storytelling-assets/media-library-card': MediaLibraryCard,
    'tut-usa/media-visual-storytelling-assets/brand-guideline-section': BrandGuidelineSection,
    'tut-usa/media-visual-storytelling-assets/color-palette': ColorPalette,
    'tut-usa/media-visual-storytelling-assets/typography-guide': TypographyGuide,
    'tut-usa/media-visual-storytelling-assets/icon-library': IconLibrary,
    'tut-usa/media-visual-storytelling-assets/design-token-table': DesignTokenTable,
    'tut-usa/media-visual-storytelling-assets/brand-asset-download': BrandAssetDownload,
    'tut-usa/media-visual-storytelling-assets/press-kit': PressKit,
    'tut-usa/media-visual-storytelling-assets/media-coverage-card': MediaCoverageCard,
    'tut-usa/media-visual-storytelling-assets/resource-card': ResourceCard,
    'tut-usa/media-visual-storytelling-assets/resource-list': ResourceList,
    // TUT USA — CTAs, Promotions & Campaigns
    'tut-usa/calls-to-action-promotions-campaigns/alert-banner': AlertBanner,
    'tut-usa/calls-to-action-promotions-campaigns/inline-alert': InlineAlert,
    'tut-usa/calls-to-action-promotions-campaigns/announcement-bar': AnnouncementBar,
    'tut-usa/calls-to-action-promotions-campaigns/hero-banner': CtasHeroBanner,
    'tut-usa/calls-to-action-promotions-campaigns/split-hero': SplitHero,
    'tut-usa/calls-to-action-promotions-campaigns/video-hero': VideoHero,
    'tut-usa/calls-to-action-promotions-campaigns/image-banner': ImageBanner,
    'tut-usa/calls-to-action-promotions-campaigns/promo-banner': PromoBanner,
    'tut-usa/calls-to-action-promotions-campaigns/cta-button': CtaButton,
    'tut-usa/calls-to-action-promotions-campaigns/featured-content': FeaturedContent,
    'tut-usa/calls-to-action-promotions-campaigns/newsletter-signup': NewsletterSignup,
    'tut-usa/calls-to-action-promotions-campaigns/email-signup': EmailSignup,
    'tut-usa/calls-to-action-promotions-campaigns/pricing-table': PricingTable,
    'tut-usa/calls-to-action-promotions-campaigns/plan-card': PlanCard,
    'tut-usa/calls-to-action-promotions-campaigns/campaign-landing-section': CampaignLandingSection,
    'tut-usa/calls-to-action-promotions-campaigns/promo-tile': PromoTile,
    'tut-usa/calls-to-action-promotions-campaigns/offer-card': OfferCard,
    'tut-usa/calls-to-action-promotions-campaigns/collection-spotlight': CollectionSpotlight,
    'tut-usa/calls-to-action-promotions-campaigns/promo-ribbon': PromoRibbon,
    'tut-usa/calls-to-action-promotions-campaigns/bundle-offer': BundleOffer,
    'tut-usa/calls-to-action-promotions-campaigns/gift-guide': GiftGuide,
    'tut-usa/calls-to-action-promotions-campaigns/donation-cta': DonationCta,
    'tut-usa/calls-to-action-promotions-campaigns/promo-card': PromoCard,
    'tut-usa/calls-to-action-promotions-campaigns/seasonal-campaign-block': SeasonalCampaignBlock,
    'tut-usa/calls-to-action-promotions-campaigns/buyer-guide': BuyerGuide,
    'tut-usa/calls-to-action-promotions-campaigns/implementation-plan': ImplementationPlan,
    'tut-usa/calls-to-action-promotions-campaigns/success-plan': SuccessPlan,
    'tut-usa/calls-to-action-promotions-campaigns/campaign-hero': CampaignHero,
    'tut-usa/calls-to-action-promotions-campaigns/product-hero': ProductHero,
    'tut-usa/calls-to-action-promotions-campaigns/event-hero': EventHero,
    'tut-usa/calls-to-action-promotions-campaigns/recruiting-hero': RecruitingHero,
    'tut-usa/calls-to-action-promotions-campaigns/investor-hero': InvestorHero,
    'tut-usa/calls-to-action-promotions-campaigns/brand-story-hero': BrandStoryHero,
    'tut-usa/calls-to-action-promotions-campaigns/offer-card-alt': OfferCardAlt,
    'tut-usa/calls-to-action-promotions-campaigns/trial-signup': TrialSignup,
    'tut-usa/calls-to-action-promotions-campaigns/demo-request-cta': DemoRequestCta,
    'tut-usa/calls-to-action-promotions-campaigns/gift-card-promo': GiftCardPromo,
    'tut-usa/calls-to-action-promotions-campaigns/sales-enablement-asset': SalesEnablementAsset,
    'tut-usa/calls-to-action-promotions-campaigns/battlecard': Battlecard,
    'tut-usa/calls-to-action-promotions-campaigns/competitive-comparison-table': CompetitiveComparisonTable,
    'tut-usa/calls-to-action-promotions-campaigns/marketplace-listing-card': MarketplaceListingCard,
    'tut-usa/calls-to-action-promotions-campaigns/persona-showcase': PersonaShowcase,
    'tut-usa/calls-to-action-promotions-campaigns/seasonal-hero': SeasonalHero,
    // TUT USA — Forms, Data Capture & Consent
    'tut-usa/forms-data-capture-consent/lead-form': LeadForm,
    'tut-usa/forms-data-capture-consent/contact-form': ContactForm,
    'tut-usa/forms-data-capture-consent/support-form': SupportForm,
    'tut-usa/forms-data-capture-consent/feedback-form': FeedbackForm,
    'tut-usa/forms-data-capture-consent/survey': Survey,
    'tut-usa/forms-data-capture-consent/poll': Poll,
    'tut-usa/forms-data-capture-consent/quiz': Quiz,
    'tut-usa/forms-data-capture-consent/calculator': Calculator,
    'tut-usa/forms-data-capture-consent/form-field-text': FormFieldText,
    'tut-usa/forms-data-capture-consent/form-field-textarea': FormFieldTextarea,
    'tut-usa/forms-data-capture-consent/form-field-email': FormFieldEmail,
    'tut-usa/forms-data-capture-consent/form-field-phone': FormFieldPhone,
    'tut-usa/forms-data-capture-consent/form-field-select': FormFieldSelect,
    'tut-usa/forms-data-capture-consent/form-field-radio-group': FormFieldRadioGroup,
    'tut-usa/forms-data-capture-consent/form-field-checkbox': FormFieldCheckbox,
    'tut-usa/forms-data-capture-consent/form-field-checkbox-group': FormFieldCheckboxGroup,
    'tut-usa/forms-data-capture-consent/form-field-date': FormFieldDate,
    'tut-usa/forms-data-capture-consent/form-field-file-upload': FormFieldFileUpload,
    'tut-usa/forms-data-capture-consent/form-field-consent': FormFieldConsent,
    'tut-usa/forms-data-capture-consent/cookie-banner': CookieBanner,
    'tut-usa/forms-data-capture-consent/privacy-notice': PrivacyNotice,
    'tut-usa/forms-data-capture-consent/terms-and-conditions': TermsAndConditions,
    'tut-usa/forms-data-capture-consent/consent-manager': ConsentManager,
    'tut-usa/forms-data-capture-consent/comment-form': CommentForm,
    'tut-usa/forms-data-capture-consent/application-form': ApplicationForm,
    'tut-usa/forms-data-capture-consent/quote-request-form': QuoteRequestForm,
    'tut-usa/forms-data-capture-consent/prescription-refill-form': PrescriptionRefillForm,
    'tut-usa/forms-data-capture-consent/returns-form': ReturnsForm,
    'tut-usa/forms-data-capture-consent/data-request-form': DataRequestForm,
    'tut-usa/forms-data-capture-consent/age-gate': AgeGate,
    'tut-usa/forms-data-capture-consent/meeting-request-form': MeetingRequestForm,
    'tut-usa/forms-data-capture-consent/idea-submission-form': IdeaSubmissionForm,
    'tut-usa/forms-data-capture-consent/helpfulness-vote': HelpfulnessVote,
    'tut-usa/forms-data-capture-consent/report-issue-link': ReportIssueLink,
    'tut-usa/forms-data-capture-consent/accessibility-statement': AccessibilityStatement,
    'tut-usa/forms-data-capture-consent/do-not-sell-link': DoNotSellLink,
    'tut-usa/forms-data-capture-consent/petition-form': PetitionForm,
    'tut-usa/forms-data-capture-consent/volunteer-signup': VolunteerSignup,
    'tut-usa/forms-data-capture-consent/membership-signup': MembershipSignup,
    'tut-usa/forms-data-capture-consent/franchise-inquiry-form': FranchiseInquiryForm,
    'tut-usa/forms-data-capture-consent/warranty-registration': WarrantyRegistration,
    'tut-usa/forms-data-capture-consent/vin-lookup': VinLookup,
    // TUT USA — Commerce, Catalog & Merchandising
    'tut-usa/commerce-catalog-merchandising/product-card': ProductCard,
    'tut-usa/commerce-catalog-merchandising/product-grid': ProductGrid,
    'tut-usa/commerce-catalog-merchandising/product-detail': ProductDetail,
    'tut-usa/commerce-catalog-merchandising/product-gallery': ProductGallery,
    'tut-usa/commerce-catalog-merchandising/product-specs': CommerceProductSpecs,
    'tut-usa/commerce-catalog-merchandising/product-variants': ProductVariants,
    'tut-usa/commerce-catalog-merchandising/add-to-cart': AddToCart,
    'tut-usa/commerce-catalog-merchandising/mini-cart': MiniCart,
    'tut-usa/commerce-catalog-merchandising/cart-summary': CartSummary,
    'tut-usa/commerce-catalog-merchandising/checkout-progress': CheckoutProgress,
    'tut-usa/commerce-catalog-merchandising/coupon-entry': CouponEntry,
    'tut-usa/commerce-catalog-merchandising/upsell-recommendation': UpsellRecommendation,
    'tut-usa/commerce-catalog-merchandising/cross-sell': CrossSell,
    'tut-usa/commerce-catalog-merchandising/wishlist-button': WishlistButton,
    'tut-usa/commerce-catalog-merchandising/saved-items-list': SavedItemsList,
    'tut-usa/commerce-catalog-merchandising/review-summary': ReviewSummary,
    'tut-usa/commerce-catalog-merchandising/review-list': ReviewList,
    'tut-usa/commerce-catalog-merchandising/star-rating': StarRating,
    'tut-usa/commerce-catalog-merchandising/review-form': ReviewForm,
    'tut-usa/commerce-catalog-merchandising/comparison-tool': ComparisonTool,
    'tut-usa/commerce-catalog-merchandising/configurator': Configurator,
    'tut-usa/commerce-catalog-merchandising/merchandise-card': MerchandiseCard,
    'tut-usa/commerce-catalog-merchandising/meal-plan-card': MealPlanCard,
    'tut-usa/commerce-catalog-merchandising/recipe-card': RecipeCard,
    'tut-usa/commerce-catalog-merchandising/recipe-detail': RecipeDetail,
    'tut-usa/commerce-catalog-merchandising/nutrition-facts': NutritionFacts,
    'tut-usa/commerce-catalog-merchandising/allergen-notice': AllergenNotice,
    'tut-usa/commerce-catalog-merchandising/returns-policy': ReturnsPolicy,
    'tut-usa/commerce-catalog-merchandising/preorder-cta': PreorderCta,
    'tut-usa/commerce-catalog-merchandising/license-selector': LicenseSelector,
    'tut-usa/commerce-catalog-merchandising/comparison-card': ComparisonCard,
    // TUT USA — Account, Portal & Transactional
    'tut-usa/account-portal-transactional/login-form': LoginForm,
    'tut-usa/account-portal-transactional/registration-form': RegistrationForm,
    'tut-usa/account-portal-transactional/password-reset': PasswordReset,
    'tut-usa/account-portal-transactional/profile-summary': ProfileSummary,
    'tut-usa/account-portal-transactional/profile-editor': ProfileEditor,
    'tut-usa/account-portal-transactional/address-block': AddressBlock,
    'tut-usa/account-portal-transactional/billing-address-form': BillingAddressForm,
    'tut-usa/account-portal-transactional/shipping-address-form': ShippingAddressForm,
    'tut-usa/account-portal-transactional/order-summary': OrderSummary,
    'tut-usa/account-portal-transactional/subscription-status': SubscriptionStatus,
    'tut-usa/account-portal-transactional/billing-history': BillingHistory,
    'tut-usa/account-portal-transactional/invoice-download': InvoiceDownload,
    'tut-usa/account-portal-transactional/payment-method-card': PaymentMethodCard,
    'tut-usa/account-portal-transactional/payment-form': PaymentForm,
    'tut-usa/account-portal-transactional/loyalty-summary': LoyaltySummary,
    'tut-usa/account-portal-transactional/rewards-card': RewardsCard,
    'tut-usa/account-portal-transactional/dashboard-widget': DashboardWidget,
    'tut-usa/account-portal-transactional/status-badge': StatusBadge,
    'tut-usa/account-portal-transactional/portal-shortcut': PortalShortcut,
    'tut-usa/account-portal-transactional/sso-button': SSOButton,
    'tut-usa/account-portal-transactional/partner-portal-link': PartnerPortalLink,
    'tut-usa/account-portal-transactional/entitlement-summary': EntitlementSummary,
    'tut-usa/account-portal-transactional/reactivation-offer': ReactivationOffer,
    'tut-usa/account-portal-transactional/member-benefit-card': MemberBenefitCard,
    // TUT USA — Events, Booking, Travel & Hospitality
    'tut-usa/events-booking-travel-hospitality/webinar-promo': WebinarPromo,
    'tut-usa/events-booking-travel-hospitality/webinar-replay': WebinarReplay,
    'tut-usa/events-booking-travel-hospitality/event-card': EventCard,
    'tut-usa/events-booking-travel-hospitality/event-list': EventList,
    'tut-usa/events-booking-travel-hospitality/event-detail': EventDetail,
    'tut-usa/events-booking-travel-hospitality/agenda': Agenda,
    'tut-usa/events-booking-travel-hospitality/speaker-profile': SpeakerProfile,
    'tut-usa/events-booking-travel-hospitality/booking-widget': BookingWidget,
    'tut-usa/events-booking-travel-hospitality/appointment-scheduler': AppointmentScheduler,
    'tut-usa/events-booking-travel-hospitality/reservation-card': ReservationCard,
    'tut-usa/events-booking-travel-hospitality/itinerary': Itinerary,
    'tut-usa/events-booking-travel-hospitality/seat-map': SeatMap,
    'tut-usa/events-booking-travel-hospitality/room-selector': RoomSelector,
    'tut-usa/events-booking-travel-hospitality/reservation-form': ReservationForm,
    'tut-usa/events-booking-travel-hospitality/delivery-slot-selector': DeliverySlotSelector,
    'tut-usa/events-booking-travel-hospitality/roadshow-schedule': RoadshowSchedule,
    'tut-usa/events-booking-travel-hospitality/venue-card': VenueCard,
    'tut-usa/events-booking-travel-hospitality/workshop-card': WorkshopCard,
    'tut-usa/events-booking-travel-hospitality/training-schedule': TrainingSchedule,
    'tut-usa/events-booking-travel-hospitality/event-card-alt': EventCardAlt,
    'tut-usa/events-booking-travel-hospitality/community-event-card': CommunityEventCard,
    'tut-usa/events-booking-travel-hospitality/expo-booth-info': ExpoBoothInfo,
    'tut-usa/events-booking-travel-hospitality/menu-card': MenuCard,
    'tut-usa/events-booking-travel-hospitality/menu-list': MenuList,
    // TUT USA — Community, Social Proof & Engagement
    'tut-usa/community-social-proof-engagement/contact-card': ContactCard,
    'tut-usa/community-social-proof-engagement/team-member-profile': TeamMemberProfile,
    'tut-usa/community-social-proof-engagement/author-bio': AuthorBio,
    'tut-usa/community-social-proof-engagement/testimonial': CommunityTestimonial,
    'tut-usa/community-social-proof-engagement/client-list': ClientList,
    'tut-usa/community-social-proof-engagement/media-contact': MediaContact,
    'tut-usa/community-social-proof-engagement/chat-widget': ChatWidget,
    'tut-usa/community-social-proof-engagement/virtual-assistant': VirtualAssistant,
    'tut-usa/community-social-proof-engagement/social-share': SocialShare,
    'tut-usa/community-social-proof-engagement/social-follow': SocialFollow,
    'tut-usa/community-social-proof-engagement/social-feed': SocialFeed,
    'tut-usa/community-social-proof-engagement/instagram-gallery': InstagramGallery,
    'tut-usa/community-social-proof-engagement/linkedin-feed': LinkedInFeed,
    'tut-usa/community-social-proof-engagement/x-feed': XFeed,
    'tut-usa/community-social-proof-engagement/trust-badges': TrustBadges,
    'tut-usa/community-social-proof-engagement/certification-list': CertificationList,
    'tut-usa/community-social-proof-engagement/award-showcase': AwardShowcase,
    'tut-usa/community-social-proof-engagement/partner-showcase': PartnerShowcase,
    'tut-usa/community-social-proof-engagement/partner-detail': PartnerDetail,
    'tut-usa/community-social-proof-engagement/community-forum-teaser': CommunityForumTeaser,
    'tut-usa/community-social-proof-engagement/discussion-thread-preview': DiscussionThreadPreview,
    'tut-usa/community-social-proof-engagement/comments': Comments,
    'tut-usa/community-social-proof-engagement/user-generated-gallery': UserGeneratedGallery,
    'tut-usa/community-social-proof-engagement/community-spotlight': CommunitySpotlight,
    'tut-usa/community-social-proof-engagement/donor-wall': DonorWall,
    'tut-usa/community-social-proof-engagement/mentor-profile': MentorProfile,
    'tut-usa/community-social-proof-engagement/champion-story': ChampionStory,
    'tut-usa/community-social-proof-engagement/vote-card': VoteCard,
    'tut-usa/community-social-proof-engagement/partner-finder': PartnerFinder,
    'tut-usa/community-social-proof-engagement/partner-tier-badge': PartnerTierBadge,
    // TUT USA — Brand, Corporate, Investor & Governance
    'tut-usa/brand-corporate-investor-governance/investor-metric': InvestorMetric,
    'tut-usa/brand-corporate-investor-governance/financial-table': FinancialTable,
    'tut-usa/brand-corporate-investor-governance/sec-filing-download': SecFilingDownload,
    'tut-usa/brand-corporate-investor-governance/earnings-call-promo': EarningsCallPromo,
    'tut-usa/brand-corporate-investor-governance/investor-contact': InvestorContact,
    'tut-usa/brand-corporate-investor-governance/compliance-notice': ComplianceNotice,
    'tut-usa/brand-corporate-investor-governance/policy-document': PolicyDocument,
    'tut-usa/brand-corporate-investor-governance/document-version-history': DocumentVersionHistory,
    'tut-usa/brand-corporate-investor-governance/internal-note': InternalNote,
    'tut-usa/brand-corporate-investor-governance/office-location': OfficeLocation,
    'tut-usa/brand-corporate-investor-governance/culture-card': CultureCard,
    'tut-usa/brand-corporate-investor-governance/benefits-list': BenefitsList,
    'tut-usa/brand-corporate-investor-governance/grant-opportunity': GrantOpportunity,
    'tut-usa/brand-corporate-investor-governance/sponsor-showcase': SponsorShowcase,
    'tut-usa/brand-corporate-investor-governance/recall-notice': RecallNotice,
    'tut-usa/brand-corporate-investor-governance/job-listing-card': JobListingCard,
    'tut-usa/brand-corporate-investor-governance/job-listings': JobListings,
    'tut-usa/brand-corporate-investor-governance/job-detail': JobDetail,
    'tut-usa/brand-corporate-investor-governance/analyst-report-promo': AnalystReportPromo,
    // TUT USA — Support, Documentation & Knowledge
    'tut-usa/support-documentation-knowledge/roadmap-section': RoadmapSection,
    'tut-usa/support-documentation-knowledge/escalation-matrix': EscalationMatrix,
    // TUT USA — Location, Local & Physical Presence
    'tut-usa/location-local-physical-presence/map-embed': MapEmbed,
    'tut-usa/location-local-physical-presence/location-card': LocationCard,
    'tut-usa/location-local-physical-presence/store-locator': StoreLocator,
    'tut-usa/location-local-physical-presence/interactive-map': InteractiveMap,
    'tut-usa/location-local-physical-presence/branch-locator': BranchLocator,
    'tut-usa/location-local-physical-presence/atm-locator': AtmLocator,
    'tut-usa/location-local-physical-presence/clinic-locator': ClinicLocator,
    'tut-usa/location-local-physical-presence/campus-location': CampusLocation,
    'tut-usa/location-local-physical-presence/provider-profile': ProviderProfile,
    'tut-usa/location-local-physical-presence/pickup-location-card': PickupLocationCard,
    'tut-usa/location-local-physical-presence/service-center-card': ServiceCenterCard,
    'tut-usa/location-local-physical-presence/location-card-alt': LocationCardAlt,
    'tut-usa/location-local-physical-presence/dealer-locator': DealerLocator,
    // TUT USA — Education, Learning & Developer Content
    'tut-usa/education-learning-developer-content/course-card': CourseCard,
    'tut-usa/education-learning-developer-content/course-catalog': CourseCatalog,
    'tut-usa/education-learning-developer-content/lesson-detail': LessonDetail,
    'tut-usa/education-learning-developer-content/certificate-download': CertificateDownload,
    'tut-usa/education-learning-developer-content/faculty-profile': FacultyProfile,
    'tut-usa/education-learning-developer-content/program-overview': ProgramOverview,
    'tut-usa/education-learning-developer-content/api-documentation-teaser': ApiDocumentationTeaser,
    'tut-usa/education-learning-developer-content/api-endpoint-reference': ApiEndpointReference,
    'tut-usa/education-learning-developer-content/sdk-download': SdkDownload,
    'tut-usa/education-learning-developer-content/sample-code': SampleCode,
    'tut-usa/education-learning-developer-content/sandbox-access-cta': SandboxAccessCta,
    'tut-usa/education-learning-developer-content/certification-path': CertificationPath,
    'tut-usa/education-learning-developer-content/integration-detail': IntegrationDetail,
    'tut-usa/education-learning-developer-content/system-requirement-list': SystemRequirementList,
  })
  .setFallback(({ data }: any) => (
    <div className="p-4 border border-dashed border-gray-300 rounded">
      <pre className="text-xs">{JSON.stringify(data, null, 2)}</pre>
    </div>
  ));
