/**
 * FlexCMS Selenium E2E — authoring matrix recorder (REB-19).
 *
 * Writes the per-component/per-field coverage rows a run produced into the task
 * artifact folder, so the evidence in `df/artifacts/{task-id}/devops/` is
 * generated by the run rather than hand-maintained. REB-26 reuses this recorder
 * for the field-level half of its exhaustive per-component sweep, and builds its
 * component-level matrix on the same CSV primitives exported here.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveRepoRoot } from '../fixtures/component-contracts';

export type MatrixOutcome = 'PASS' | 'FAIL' | 'BLOCKED' | 'SKIPPED';

export interface MatrixRow {
  scenarioId: string;
  groupName: string;
  resourceType: string;
  componentTitle: string;
  fieldKey: string;
  editorControl: string;
  fieldSemantics: string;
  /** What the row proves: `ui`, `author-api`, `headless`, `rendered`, `publish`. */
  verifiedLayers: string;
  outcome: MatrixOutcome;
  notes: string;
}

const CSV_HEADER = [
  'scenarioId',
  'groupName',
  'resourceType',
  'componentTitle',
  'fieldKey',
  'editorControl',
  'fieldSemantics',
  'verifiedLayers',
  'outcome',
  'notes',
] as const;

/** CSV-escapes one cell, collapsing newlines so every row stays a single line. */
export function escapeCsv(value: string): string {
  const normalized = value.replace(/\r?\n/g, ' ').trim();
  return /[",]/.test(normalized) ? `"${normalized.replace(/"/g, '""')}"` : normalized;
}

/** Absolute path of a CSV inside a task's `devops` artifact folder. */
export function artifactCsvPath(taskId: string, fileName: string): string {
  return path.join(resolveRepoRoot(), 'df', 'artifacts', taskId, 'devops', fileName);
}

/**
 * Writes one CSV into a task's `devops` artifact folder and returns its path.
 * Shared by every recorder so escaping and artifact layout stay identical.
 */
export function writeCsvFile<TRow extends object>(
  taskId: string,
  fileName: string,
  header: ReadonlyArray<keyof TRow & string>,
  rows: readonly TRow[],
): string {
  const target = artifactCsvPath(taskId, fileName);
  fs.mkdirSync(path.dirname(target), { recursive: true });

  const lines = [header.join(',')];
  for (const row of rows) {
    lines.push(header.map((column) => escapeCsv(String(row[column] ?? ''))).join(','));
  }

  fs.writeFileSync(target, `${lines.join('\n')}\n`, 'utf8');
  return target;
}

export class MatrixRecorder {
  private readonly rows: MatrixRow[] = [];

  /**
   * @param taskId   task whose artifact folder receives the CSV
   * @param fileName CSV name; REB-26 writes field-level detail next to its
   *                 component-level matrix, so the name is caller-controlled.
   */
  constructor(
    private readonly taskId: string,
    private readonly fileName: string = 'matrix-coverage.csv',
  ) {}

  add(row: MatrixRow): void {
    this.rows.push(row);
  }

  get size(): number {
    return this.rows.length;
  }

  countByOutcome(outcome: MatrixOutcome): number {
    return this.rows.filter((row) => row.outcome === outcome).length;
  }

  /** Absolute path of the CSV this recorder writes. */
  targetPath(): string {
    return artifactCsvPath(this.taskId, this.fileName);
  }

  write(): string {
    return writeCsvFile(this.taskId, this.fileName, CSV_HEADER, this.rows);
  }
}
