import * as fs from 'node:fs';
import * as path from 'node:path';

type PageKind = 'templates' | 'components';

interface GlobalManifestPage {
  kind: PageKind;
  slug: string;
  manifestPath: string;
  normalizedHtml: string;
  screenshotEvidence: string;
  blockerCount: number;
}

interface GlobalManifest {
  generatedAt: string;
  pages: GlobalManifestPage[];
  skippedFolders: Array<{ kind: PageKind; slug: string; reason: string }>;
}

interface TemplateContract {
  name: string;
  title: string;
  templateSource?: {
    folder?: string;
  };
}

interface ComponentContract {
  groupName: string;
  resourceType: string;
}

interface TemplateFixture {
  caseId: string;
  slug: string;
  title: string;
  captureStatus: 'captured' | 'skipped';
  manifestPath: string;
  normalizedHtml: string;
  screenshotEvidence: string;
  blockerCount: number;
}

interface ComponentFixture {
  caseId: string;
  slug: string;
  title: string;
  captureStatus: 'captured' | 'skipped';
  manifestPath: string;
  normalizedHtml: string;
  screenshotEvidence: string;
  blockerCount: number;
}

const packageRoot = path.resolve(__dirname, '../..');
const repoRoot = path.resolve(packageRoot, '../../..');
const designRoot = path.join(repoRoot, 'Design', 'tut-usa');
const generatedRoot = path.join(designRoot, 'generated');
const manifestPath = path.join(designRoot, 'manifest.json');
const templateContractsPath = path.join(generatedRoot, 'template-contracts.json');
const componentContractsPath = path.join(generatedRoot, 'component-contracts.json');

const fixturesRoot = path.join(packageRoot, 'src', 'fixtures');
const templateCasesRoot = path.join(packageRoot, 'src', 'cases', 'templates');
const componentCasesRoot = path.join(packageRoot, 'src', 'cases', 'components');

function main(): void {
  const manifest = readJson<GlobalManifest>(manifestPath);
  const templateContracts = readJson<TemplateContract[]>(templateContractsPath);
  const componentContracts = readJson<ComponentContract[]>(componentContractsPath);

  const templateTitleBySlug = buildTemplateTitleMap(templateContracts);
  const componentTitleBySlug = buildComponentTitleMap(componentContracts);

  const templatePages = mergePagesWithSkipped(manifest, 'templates');
  const componentPages = mergePagesWithSkipped(manifest, 'components');

  const templateFixtures: TemplateFixture[] = templatePages.map((page, index) => ({
    caseId: `TPL-${pad(index + 1)}`,
    slug: page.slug,
    title: templateTitleBySlug.get(page.slug) ?? titleFromSlug(page.slug),
    captureStatus: page.kind === 'templates' && page.manifestPath ? 'captured' : 'skipped',
    manifestPath: page.manifestPath,
    normalizedHtml: page.normalizedHtml,
    screenshotEvidence: page.screenshotEvidence,
    blockerCount: page.blockerCount,
  }));

  const componentFixtures: ComponentFixture[] = componentPages.map((page, index) => ({
    caseId: `CMP-${pad(index + 1)}`,
    slug: page.slug,
    title: componentTitleBySlug.get(page.slug) ?? titleFromComponentSlug(page.slug),
    captureStatus: page.kind === 'components' && page.manifestPath ? 'captured' : 'skipped',
    manifestPath: page.manifestPath,
    normalizedHtml: page.normalizedHtml,
    screenshotEvidence: page.screenshotEvidence,
    blockerCount: page.blockerCount,
  }));

  ensureDir(fixturesRoot);
  ensureDir(templateCasesRoot);
  ensureDir(componentCasesRoot);
  ensureDir(generatedRoot);

  writeTemplateFixtureFile(templateFixtures);
  writeComponentFixtureFile(componentFixtures);
  writeFixturesIndex();

  writeTemplateSpecSkeletons(templateFixtures);
  writeComponentSpecSkeletons(componentFixtures);

  writeTraceabilityCsv(templateFixtures, componentFixtures, manifest.generatedAt);

  console.log(
    `[REB-06] Generated ${templateFixtures.length} template fixtures/spec skeletons and ${componentFixtures.length} component fixtures/spec skeletons.`,
  );
}

function writeTemplateFixtureFile(fixtures: TemplateFixture[]): void {
  const body = [
    '/**',
    ' * Generated by `src/capture/generateTraceabilitySkeletons.ts` for REB-06.',
    ' * Do not hand-edit; regenerate with `pnpm generate:traceability`.',
    ' */',
    'export interface TemplateManifestEntry {',
    '  caseId: string;',
    '  slug: string;',
    '  title: string;',
    "  captureStatus: 'captured' | 'skipped';",
    '  manifestPath: string;',
    '  normalizedHtml: string;',
    '  screenshotEvidence: string;',
    '  blockerCount: number;',
    '}',
    '',
    `export const templateManifest: TemplateManifestEntry[] = ${JSON.stringify(fixtures, null, 2)};`,
    '',
  ].join('\n');

  fs.writeFileSync(path.join(fixturesRoot, 'template-manifest.ts'), body, 'utf8');
}

function writeComponentFixtureFile(fixtures: ComponentFixture[]): void {
  const body = [
    '/**',
    ' * Generated by `src/capture/generateTraceabilitySkeletons.ts` for REB-06.',
    ' * Do not hand-edit; regenerate with `pnpm generate:traceability`.',
    ' */',
    'export interface ComponentManifestEntry {',
    '  caseId: string;',
    '  slug: string;',
    '  title: string;',
    "  captureStatus: 'captured' | 'skipped';",
    '  manifestPath: string;',
    '  normalizedHtml: string;',
    '  screenshotEvidence: string;',
    '  blockerCount: number;',
    '}',
    '',
    `export const componentManifest: ComponentManifestEntry[] = ${JSON.stringify(fixtures, null, 2)};`,
    '',
  ].join('\n');

  fs.writeFileSync(path.join(fixturesRoot, 'component-manifest.ts'), body, 'utf8');
}

function writeFixturesIndex(): void {
  const body = [
    "export { templateManifest } from './template-manifest';",
    "export { componentManifest } from './component-manifest';",
    '',
  ].join('\n');

  fs.writeFileSync(path.join(fixturesRoot, 'index.ts'), body, 'utf8');
}

function writeTemplateSpecSkeletons(fixtures: TemplateFixture[]): void {
  for (const fixture of fixtures) {
    const filePath = path.join(templateCasesRoot, `${fixture.slug}.spec.ts`);
    fs.writeFileSync(filePath, buildTemplateSpec(fixture), 'utf8');
  }
}

function writeComponentSpecSkeletons(fixtures: ComponentFixture[]): void {
  for (const fixture of fixtures) {
    const filePath = path.join(componentCasesRoot, `${fixture.slug}.spec.ts`);
    fs.writeFileSync(filePath, buildComponentSpec(fixture), 'utf8');
  }
}

function buildTemplateSpec(fixture: TemplateFixture): string {
  return [
    '/**',
    ' * Generated REB-06 skeleton spec. Implementation is intentionally deferred to REB-12.',
    ' */',
    `describe('[REB-06 skeleton] Template ${fixture.caseId} - ${escapeSingleQuotes(fixture.title)}', function () {`,
    '  this.timeout(60_000);',
    '',
    `  it.skip('${fixture.caseId} checks for broken images on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks for font loading failures on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks browser console errors on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks primary CTA availability and behavior on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks responsive breakpoints on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} runs basic accessibility assertions on ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '});',
    '',
  ].join('\n');
}

function buildComponentSpec(fixture: ComponentFixture): string {
  return [
    '/**',
    ' * Generated REB-06 skeleton spec. Implementation is intentionally deferred to REB-12.',
    ' */',
    `describe('[REB-06 skeleton] Component group ${fixture.caseId} - ${escapeSingleQuotes(fixture.title)}', function () {`,
    '  this.timeout(60_000);',
    '',
    `  it.skip('${fixture.caseId} checks for broken images in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks for font loading failures in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks browser console errors in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks primary CTA availability and behavior in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} checks responsive breakpoints in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '',
    `  it.skip('${fixture.caseId} runs basic accessibility assertions in ${fixture.slug}', async () => {`,
    "    throw new Error('Implement in REB-12');",
    '  });',
    '});',
    '',
  ].join('\n');
}

function writeTraceabilityCsv(
  templates: TemplateFixture[],
  components: ComponentFixture[],
  generatedAt: string,
): void {
  const headers = [
    'entity_kind',
    'case_id',
    'title',
    'slug',
    'spec_path',
    'manifest_path',
    'normalized_html',
    'screenshot_evidence',
    'blocker_count',
    'coverage_broken_images',
    'coverage_font_loading',
    'coverage_console_errors',
    'coverage_primary_cta',
    'coverage_responsive_breakpoints',
    'coverage_basic_accessibility',
    'status',
    'notes',
  ];

  const rows: string[][] = [];

  for (const fixture of templates) {
    rows.push([
      'template',
      fixture.caseId,
      fixture.title,
      fixture.slug,
      `frontend/apps/selenium-e2e/src/cases/templates/${fixture.slug}.spec.ts`,
      fixture.manifestPath,
      fixture.normalizedHtml,
      fixture.screenshotEvidence,
      String(fixture.blockerCount),
      'planned',
      'planned',
      'planned',
      'planned',
      'planned',
      'planned',
      fixture.captureStatus === 'captured' ? 'skeleton' : 'skeleton-no-capture',
      fixture.captureStatus === 'captured'
        ? 'Generated by REB-06; implementation deferred to REB-12.'
        : 'Generated by REB-06; source folder exists but capture evidence was skipped in REB-02.',
    ]);
  }

  for (const fixture of components) {
    rows.push([
      'component-group',
      fixture.caseId,
      fixture.title,
      fixture.slug,
      `frontend/apps/selenium-e2e/src/cases/components/${fixture.slug}.spec.ts`,
      fixture.manifestPath,
      fixture.normalizedHtml,
      fixture.screenshotEvidence,
      String(fixture.blockerCount),
      'planned',
      'planned',
      'planned',
      'planned',
      'planned',
      'planned',
      fixture.captureStatus === 'captured' ? 'skeleton' : 'skeleton-no-capture',
      fixture.captureStatus === 'captured'
        ? 'Generated by REB-06; implementation deferred to REB-12.'
        : 'Generated by REB-06; source folder exists but capture evidence was skipped in REB-02.',
    ]);
  }

  const fileBody = [
    `# generated_at=${generatedAt}`,
    headers.join(','),
    ...rows.map((row) => row.map(csvEscape).join(',')),
    '',
  ].join('\n');

  fs.writeFileSync(path.join(generatedRoot, 'qa-traceability-matrix.csv'), fileBody, 'utf8');
}

function buildTemplateTitleMap(contracts: TemplateContract[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const contract of contracts) {
    const folder = contract.templateSource?.folder;
    if (folder) {
      map.set(path.basename(folder), contract.title);
    }
    map.set(toSnakeCase(contract.name), contract.title);
  }
  return map;
}

function buildComponentTitleMap(contracts: ComponentContract[]): Map<string, string> {
  const map = new Map<string, string>();
  const grouped = new Map<string, Set<string>>();

  for (const contract of contracts) {
    const groupSlug = `component_library_${toSnakeCase(contract.groupName)}`;
    if (!grouped.has(groupSlug)) {
      grouped.set(groupSlug, new Set<string>());
    }
    grouped.get(groupSlug)!.add(contract.groupName);
  }

  for (const [slug, names] of grouped.entries()) {
    map.set(slug, Array.from(names).sort()[0]);
  }

  return map;
}

function mergePagesWithSkipped(manifest: GlobalManifest, kind: PageKind): GlobalManifestPage[] {
  const bySlug = new Map<string, GlobalManifestPage>();

  for (const page of manifest.pages) {
    if (page.kind === kind) {
      bySlug.set(page.slug, page);
    }
  }

  for (const skipped of manifest.skippedFolders ?? []) {
    if (skipped.kind !== kind || bySlug.has(skipped.slug)) {
      continue;
    }
    bySlug.set(skipped.slug, {
      kind,
      slug: skipped.slug,
      manifestPath: '',
      normalizedHtml: '',
      screenshotEvidence: '',
      blockerCount: 0,
    });
  }

  return Array.from(bySlug.values()).sort(sortBySlug);
}

function sortBySlug(left: GlobalManifestPage, right: GlobalManifestPage): number {
  return left.slug.localeCompare(right.slug);
}

function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function titleFromSlug(slug: string): string {
  return slug
    .split('_')
    .map(capitalize)
    .join(' ');
}

function titleFromComponentSlug(slug: string): string {
  return titleFromSlug(slug.replace(/^component_library_/, ''));
}

function toSnakeCase(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function capitalize(value: string): string {
  return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;
}

function pad(value: number): string {
  return String(value).padStart(2, '0');
}

function ensureDir(dirPath: string): void {
  fs.mkdirSync(dirPath, { recursive: true });
}

function readJson<T>(filePath: string): T {
  const raw = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(raw) as T;
}

function escapeSingleQuotes(value: string): string {
  return value.replace(/'/g, "\\'");
}

main();

