# Publish environment profile
flexcms:
  runmode: publish
  features:
    authoring-ui: false
    workflows: false
    preview: false
    replication-receiver: true
    dam-upload: false
    version-management: false
  cache:
    redis:
      enabled: true
    warming:
      enabled: true
      publish-base-url: http://localhost:8081
      paths:
        - /
      concurrency: 4
      connect-timeout-ms: 5000
      read-timeout-ms: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flexcms_publish

server:
  port: 8081

